Add : del votes and language top voters
MineWeb/Plugin-Vote pull request #21
Opened 2018-10-30 15:13 UTC by nivcoo

2018-11-04 15:19 UTC, Eywek requested changes

2018-11-04 15:19 UTC, Eywek commented on SQL/schema.php
> +        'deletedAt' => array('type' => 'datetime', 'null' => false, 'default' => null),
Le snakecase c'est mieux pour être cohérent avec ce qui est déjà en place. Donc plutôt `deleted_at`.

2018-11-04 19:57 UTC, nivcoo commented
Voila

2018-11-13 16:46 UTC, Eywek approved these changes

2018-11-13 16:46 UTC, merged