Back version
MineWeb/Plugin-Vote pull request #23
Opened 2018-11-13 17:40 UTC by nivcoo

Le temps que le bug de l'update n'est pas corrigé

2018-11-15 09:17 UTC, mitchou06 commented
Bonjour merci pour réaliser de bons plugins mais suite à la mise à jour du plugin vote celui ci ne fonctionne plus. Pourriez vous vérifier merci.

2018-11-15 18:03 UTC, nivcoo commented
Suffit de venir sur le discord pour corriger le bug

2019-03-03 13:44 UTC, Eywek requested changes

2019-03-03 13:44 UTC, Eywek commented on SQL/schema.php
> +        'deleted_at' => array('type' => 'datetime', 'null' => false, 'default' => '2642-11-14 07:30:00'),
Mettre a null ca serait mieux justement

2019-03-03 15:42 UTC, Eywek commented
https://github.com/MineWeb/Plugin-Vote/commit/e7956817d855b60e8d8a4dea6e90768185771d00

2019-03-03 15:42 UTC, closed without merging