Edit. Vote reqard waiting
MineWeb/Plugin-Vote pull request #26
Opened 2019-02-03 13:49 UTC by nivcoo

2019-03-03 13:48 UTC, Eywek requested changes

2019-03-03 13:48 UTC, Eywek commented on Controller/VoteController.php
> +        $server_id = $findVote[0]['Website']['server_id'];
C'est pas ouf ça, prendre le premier serveur comme ça, random

2019-05-10 21:27 UTC, nivcoo commented on Controller/VoteController.php
> +        $server_id = $findVote[0]['Website']['server_id'];
Pourquoi ? il faut bien commencer par un site ^^ PS: c'est pas random c'est le premier site de $findVote donc il correspond au premier site de la liste de vote de la personne logiquement ^^

2019-08-01 12:25 UTC, Eywek commented on Controller/VoteController.php
> +        $server_id = $findVote[0]['Website']['server_id'];
Bah utilise celui configuré pour la récompense plutôt

2019-08-01 12:27 UTC, nivcoo commented
C’est pas un recompense qui est liée à un serveur mais un site donc c’est très bien de commencer par le premier site et donc toute les récompenses du même serveur puis d’un autre etc ( je l’ai sur mon serveur depuis 4 mois ça pose 0 problème)

________________________________
De : Valentin T. <notifications@github.com>
Envoyé : Thursday, August 1, 2019 2:25:37 PM
À : MineWeb/Plugin-Vote <Plugin-Vote@noreply.github.com>
Cc : nivcoo <nico64800@live.fr>; Author <author@noreply.github.com>
Objet : Re: [MineWeb/Plugin-Vote] Edit. Vote reward waiting (#26)


@Eywek requested changes on this pull request.

________________________________

In Controller/VoteController.php<https://github.com/MineWeb/Plugin-Vote/pull/26#discussion_r309669186>:

>          if (empty($findVote))

             throw new NotFoundException();

         // Give it

         $this->loadModel('Vote.Reward');

-        $reward = $findVote['Reward'];

-        if (!$this->Reward->collect($reward, $findVote['Website']['server_id'], $this->User->getKey('pseudo'), $this->Server, [$this->__getConfig()->global_command])) {

-            $this->Session->setFlash($this->Lang->get('VOTE__COLLECT_REWARD_ERROR'), 'default.error');

-            $this->redirect($this->referer());

-            return;

+        $this->loadModel('Vote.Website');

+        $server_id = $findVote[0]['Website']['server_id'];



Bah utilise celui configuré pour la récompense plutôt

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/MineWeb/Plugin-Vote/pull/26?email_source=notifications&email_token=AIWSXQB7TUJGEN5JBJ2E5RLQCLI4DA5CNFSM4GUAO2HKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCAIYCXI#pullrequestreview-269582685>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AIWSXQFKIEI6A3LHTJCRZPDQCLI4DANCNFSM4GUAO2HA>.

2019-08-01 12:46 UTC, Eywek commented
Non mais c'est moche. En plus là actuellement si tu as 2 recompenses en attente et que la deuxieme fail, la premiere ne sera pas sauvegardé comme collecté. Jvais clean tout ça

2019-08-01 13:04 UTC, Eywek commented
Good, si tu peux test du coup stp

2019-08-07 13:21 UTC, nivcoo commented
Marche pas et j'arrive pas a le faire marcher, tu use des variables qui sont pas déclaré donc je comprends pas

2019-08-07 13:29 UTC, nivcoo commented
Enfin le probleme vient du array_reduce surtout

2019-08-07 13:35 UTC, Eywek commented
Oui j’ai juste oublié de renommer `collectedVotes` par `collectedVotesByServer` partout

2019-08-07 13:35 UTC, nivcoo commented
Oui je l'ai fais ca mais juste le array dans le update all que j'arrive pas a corrigé

2019-08-07 13:39 UTC, Eywek commented
Voilà j'ai fix des trucs tu peux re-test

2019-08-07 13:40 UTC, nivcoo commented
Le problème du updateAll est toujours pas resolue

2019-08-07 13:40 UTC, nivcoo commented
[PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'where clause'

2019-08-07 13:40 UTC, nivcoo commented
Et le array reduce complet donne ca https://pics.edensky.fr/2019-08-07_15-40pHLY.png

2019-08-07 13:42 UTC, Eywek commented
Right mb, ré-essaye mtn

2019-08-07 13:45 UTC, nivcoo commented
Alors oui sa marche par contre quand tu es pas co ca mets Succès : Vous avez bien reçu votre récompense ! Mais ca donne pas de recompenses donc ca marche a moitié mdr

2019-08-07 13:46 UTC, nivcoo commented
if (!$this->Reward->collect($reward, $vote['Website']['server_id'], $this->User->getKey('pseudo'), $this->Server))
                continue;

Ca doit être le continue, il faudrai continue et envoyer une reponse

2019-08-07 13:46 UTC, Eywek commented
Oe c'est juste le msg c'est rien, ca prends 2sec att

2019-08-07 13:47 UTC, nivcoo commented
$this->Session->setFlash($this->Lang->get('VOTE__COLLECT_REWARD_ERROR'), 'default.error');

2019-08-07 13:48 UTC, Eywek commented
Voilà

2019-08-07 13:49 UTC, Eywek approved these changes

2019-08-07 13:51 UTC, nivcoo commented
Error: [Error] Call to a member function collect() on null Quand il y a qu'une recompense en attente

2019-08-07 13:52 UTC, Eywek commented
Faut donner les messages d’erreur en entier par contre stp

2019-08-07 13:52 UTC, nivcoo commented
2019-08-07 15:50:45 Error: [Error] Call to a member function collect() on null
Request URL: /vote/collect
Stack Trace:
#0 [internal function]: VoteController->getNotCollectedReward()
#1 /var/www/html/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(VoteController), Array)
#2 /var/www/html/lib/Cake/Routing/Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/html/lib/Cake/Routing/Dispatcher.php(165): Dispatcher->_invoke(Object(VoteController), Object(CakeRequest))
#4 /var/www/html/app/webroot/index.php(114): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}

2019-08-07 13:59 UTC, nivcoo commented
Non c'etait un problème de cache :p vive cake

2019-10-27 16:54 UTC, Eywek commented
conflicts

2019-11-24 13:12 UTC, Eywek commented
conflicts toujours

2019-11-24 13:31 UTC, nivcoo commented
Voila enfin ahah

2019-11-24 13:43 UTC, merged