Add top vote
MineWeb/Plugin-Vote pull request #4
Opened 2018-04-29 00:10 UTC by nivcoo

Ajout d'un top vote, qui permet de récupérer le top vote des mois et même des années précédentes. Ce code m'a été donné par arckene.

2018-04-29 00:44 UTC, Xavoux commented
Fonctionnel !!

2018-04-29 14:41 UTC, Eywek requested changes

2018-04-29 14:41 UTC, Eywek commented on Controller/TopController.php
> +    {
Une fonction pour ça c'est pas vraiment utile. Il suffirait de passer une variable à la vue avec
```php
$this->set('months', ['janvier', ...]);
```

2018-04-29 14:41 UTC, Eywek commented on Model/Top.php
> + * Date: 07/03/2018
Ce model est totalement inutile, la fonctionnalité se base sur une table déjà existante

2018-04-29 14:41 UTC, Eywek commented on View/Top/admin_index.ctp
> +                    $top = ClassRegistry::init('Vote.Vote')->find('all', [
Alors non, on ne fais pas des requêtes à la base de données dans les vues, c'est surtout ce qu'il faut éviter de faire avec du MVC. Il faut donc mettre ça dans le controller.

2018-04-30 07:20 UTC, Eywek commented
Duplicate #7

2018-04-30 07:20 UTC, closed without merging