TOP VOTEUR + STATS
MineWeb/Plugin-Vote pull request #7
Opened 2018-04-29 23:09 UTC by ThomasFar06

Ajout d'un top voteur et de stats

2018-04-30 07:16 UTC, Eywek requested changes

2018-04-30 07:16 UTC, Eywek commented on View/Top/admin_index.ctp
> +foreach($months as $var)
Ça, ça se calcule dans les controllers également

2018-04-30 08:15 UTC, ThomasFar06 commented on View/Top/admin_index.ctp
> +foreach($months as $var)
tes chiants omd

2018-05-08 10:09 UTC, Eywek requested changes

2018-05-08 10:09 UTC, Eywek commented on config.json
> +					"permission": "VOTE__ADMIN_VIEW_TOP",
Il faut aussi ajouter cette permission aux permissions.available

2018-05-08 10:19 UTC, Eywek approved these changes

2018-05-08 10:19 UTC, merged